export const countries = [
  { label: "Afghanistan", value: "afghanistan" },
  { label: "Argentina", value: "argentina" },
  { label: "Australia", value: "australia" },
  { label: "Austria", value: "austria" },
  { label: "Bangladesh", value: "bangladesh" },
  { label: "Belgium", value: "belgium" },
  { label: "Brazil", value: "brazil" },
  { label: "Canada", value: "canada" },
  { label: "China", value: "china" },
  { label: "Denmark", value: "denmark" },
  { label: "Egypt", value: "egypt" },
  { label: "Finland", value: "finland" },
  { label: "France", value: "france" },
  { label: "Germany", value: "germany" },
  { label: "India", value: "india" },
  { label: "Indonesia", value: "indonesia" },
  { label: "Italy", value: "italy" },
  { label: "Japan", value: "japan" },
  { label: "Mexico", value: "mexico" },
  { label: "Netherlands", value: "netherlands" },
  { label: "New Zealand", value: "new_zealand" },
  { label: "Nigeria", value: "nigeria" },
  { label: "Norway", value: "norway" },
  { label: "Pakistan", value: "pakistan" },
  { label: "Russia", value: "russia" },
  { label: "Saudi Arabia", value: "saudi_arabia" },
  { label: "Singapore", value: "singapore" },
  { label: "South Africa", value: "south_africa" },
  { label: "South Korea", value: "south_korea" },
  { label: "Spain", value: "spain" },
  { label: "Sweden", value: "sweden" },
  { label: "Switzerland", value: "switzerland" },
  { label: "Thailand", value: "thailand" },
  { label: "Turkey", value: "turkey" },
  { label: "United Arab Emirates", value: "uae" },
  { label: "United Kingdom", value: "uk" },
  { label: "United States", value: "usa" },
  { label: "Vietnam", value: "vietnam" },
];